#server:
#  port: 9012
#  
#spring:
#  application: 
#    name: tensquare-web
#    
#eureka:
#  instance: 
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:6868/eureka/
#      
#zuul:
#  routes:
#    tensquare-base: # 基础微服务
#      path: /base/** # 配置请求URL的请求规则
#      serviceId: tensquare-base # 指定Eureka注册中心的服务id   
#    tensquare-user: 
#      path: /user/** 
#      serviceId: tensquare-user
#    tensquare-qa: 
#      path: /qa/** 
#      serviceId: tensquare-qa         