server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruid
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.156.61:3306/tensquare_recruit
    username: root
    password: 123456
  jpa: 
    database: mysql
    show-sql: true
