#server: 
#  port: 9001
#  
#spring: 
#  application: 
#    name: tensquare-base
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.156.61:3306/tensquare_base
#    username: root
#    password: 123456
#  jpa: 
#    database: mysql
#    show-sql: true
#    
#eureka:
#  instance: 
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:6868/eureka/ 